# GNU Make solution makefile autogenerated by Premake

ifndef config
  config=release_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release_x64)
  fieldfit_config = release_x64
endif

PROJECTS := fieldfit

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

fieldfit:
ifneq (,$(fieldfit_config))
	@echo "==== Building fieldfit ($(fieldfit_config)) ===="
	@${MAKE} --no-print-directory -C . -f fieldfit.make config=$(fieldfit_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f fieldfit.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   fieldfit"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
